### ISSUE TITLE
Install issues: BroccoliMergeTrees failure

### ISSUE THREAD

**Issue by dirkdirk** [kaliber5/ember-bootstrap-power-select#4]
Already installed via npm:
`"ember-bootstrap": "1.0.0-rc.1",`

Next:
`$ ember install ember-bootstrap-power-select`
`$ ember server`

Got error:
`The Broccoli Plugin: [BroccoliMergeTrees: Addon#compileAddon(ember-basic-dropdown) ] failed`

Try:
Stop ember server.
`$ ember install ember-basic-dropdown`
`$ ember server`

Then error:
`The Broccoli Plugin: [BroccoliMergeTrees: Addon#compileAddon(ember-concurrency) ] failed`

Try:
Stop ember server.
`$ ember install ember-concurrency`
`$ ember server`

Now error:
`The Broccoli Plugin: [BroccoliMergeTrees: Addon#compileAddon(ember-power-select) ] failed`

But ember-power-select is already installed.

Try: 
Stop ember server
Edit `app/package.json`:
- From: `"ember-power-select": "1.9.2",`
- To: `"ember-power-select": "1.8.5",`
- Reason: [ember-power-select ^1.9.1](https://github.com/cibernox/ember-power-select/releases) "Use new modules API."

`$ npm install`
`$ ember server`

Next error:
None!

Haven't actually used the add-on yet but will report any issues at least ember server compiles and the app works as before the above issues.

**Comment by simonihmig** [comment]
I was not able to reproduce this. Can you please post the full error stack that is shown? Or maybe create a minimal reproduction app?

Also, if missing dependencies are the problem, did you try a clean install with `rm -rf node_modules && npm install`?

**Comment by dirkdirk** [comment]
Yes, I did try nuking node_modules and `$ npm install` to no avail.

Here's all the error stacks ... hope it helps.

| Dirk on Dirks-iMac at ~/www/fivestarpodcast
| git branch - (power-select)
| 🖥  > ems
ember server
Livereload server on http://localhost:49153
Serving on http://localhost:4200/
'instrument' is imported from external module 'ember-data/-debug' but never used
The Broccoli Plugin: [BroccoliMergeTrees: Addon#compileAddon(ember-basic-dropdown) ] failed with:
TypeError: The plugin [null,{"envFlags":{"source":"@glimmer/env","flags":{"DEBUG":true,"CI":false}},"externalizeHelpers":{"global":"Ember"},"debugTools":{"source":"@ember/debug","assertPredicateIndex":1}}] didn't export a Plugin instance
    at PluginManager.validate (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at /Users/Dirk/www/fivestarpodcast/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:102:26
    at initializePromise (/Users/Dirk/www/fivestarpodcast/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/Users/Dirk/www/fivestarpodcast/node_modules/rsvp/dist/rsvp.js:1039:33)
    at Object.transformString (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:101:12)
    at Babel.transform (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-babel-transpiler/index.js:110:22)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-merge-trees/index.js:36:53)
    at mergeTrees (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:32:14)
    at Class.compileAddon (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:747:12)
    at Class.treeForAddon (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:514:26)
    at Class._treeFor (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:371:33)
    at Class.treeFor (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:339:21)
    at /Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:254:34
    at Array.map (native)


cleaning up...
|
| Dirk on Dirks-iMac at ~/www/fivestarpodcast
| git branch - (power-select)
| 🖥  > ems
ember server
Livereload server on http://localhost:49153
Serving on http://localhost:4200/
'instrument' is imported from external module 'ember-data/-debug' but never used
The Broccoli Plugin: [BroccoliMergeTrees: Addon#compileAddon(ember-concurrency) ] failed with:
TypeError: The plugin [null,{"envFlags":{"source":"@glimmer/env","flags":{"DEBUG":true,"CI":false}},"externalizeHelpers":{"global":"Ember"},"debugTools":{"source":"@ember/debug","assertPredicateIndex":1}}] didn't export a Plugin instance
    at PluginManager.validate (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at /Users/Dirk/www/fivestarpodcast/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:102:26
    at initializePromise (/Users/Dirk/www/fivestarpodcast/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/Users/Dirk/www/fivestarpodcast/node_modules/rsvp/dist/rsvp.js:1039:33)
    at Object.transformString (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:101:12)
    at Babel.transform (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-babel-transpiler/index.js:110:22)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-merge-trees/index.js:36:53)
    at mergeTrees (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:32:14)
    at Class.compileAddon (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:747:12)
    at Class.treeForAddon (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:514:26)
    at Class._treeFor (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:371:33)
    at Class.treeFor (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:339:21)
    at /Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:254:34
    at Array.map (native)


cleaning up...
| 
| Dirk on Dirks-iMac at ~/www/fivestarpodcast
| git branch - (power-select)
| 🖥  > ems
ember server
Livereload server on http://localhost:49153
Serving on http://localhost:4200/
'instrument' is imported from external module 'ember-data/-debug' but never used
The Broccoli Plugin: [BroccoliMergeTrees: Addon#compileAddon(ember-power-select) ] failed with:
TypeError: The plugin [null,{"envFlags":{"source":"@glimmer/env","flags":{"DEBUG":true,"CI":false}},"externalizeHelpers":{"global":"Ember"},"debugTools":{"source":"@ember/debug","assertPredicateIndex":1}}] didn't export a Plugin instance
    at PluginManager.validate (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/Dirk/www/fivestarpodcast/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at /Users/Dirk/www/fivestarpodcast/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:102:26
    at initializePromise (/Users/Dirk/www/fivestarpodcast/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/Users/Dirk/www/fivestarpodcast/node_modules/rsvp/dist/rsvp.js:1039:33)
    at Object.transformString (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:101:12)
    at Babel.transform (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-babel-transpiler/index.js:110:22)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/Users/Dirk/www/fivestarpodcast/node_modules/broccoli-merge-trees/index.js:36:53)
    at mergeTrees (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:32:14)
    at Class.compileAddon (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:747:12)
    at Class.treeForAddon (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:514:26)
    at Class._treeFor (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:371:33)
    at Class.treeFor (/Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/models/addon.js:339:21)
    at /Users/Dirk/www/fivestarpodcast/node_modules/ember-cli/lib/broccoli/ember-app.js:499:20
    at Array.map (native)


cleaning up...
|
| Dirk on Dirks-iMac at ~/www/fivestarpodcast
| git branch - (power-select)
| 🖥  > ems
ember server
Livereload server on http://localhost:49153
Serving on http://localhost:4200/
'instrument' is imported from external module 'ember-data/-debug' but never used

Build successful - 16277ms.

Slowest Nodes (totalTime => 5% )              | Total (avg)         
----------------------------------------------+---------------------
Babel (54)                                    | 7064ms (130 ms)     
ember-browserify (2)                          | 2371ms (1185 ms)    
Concat (8)                                    | 1321ms (165 ms)

**Comment by dirkdirk** [comment]
Here's `package.json` content:

{
  "name": "fivestarpodcast",
  "version": "0.0.0",
  "description": "Small description for fivestarpodcast goes here",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "devDependencies": {
    "aws-sdk": "^2.86.0",
    "bootstrap-sass": "3.3.7",
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^2.4.1",
    "ember-basic-dropdown": "0.33.2",
    "ember-bootstrap": "1.0.0-rc.1",
    "ember-bootstrap-power-select": "1.0.0-alpha.1",
    "ember-browserify": "^1.2.0",
    "ember-cli": "2.10.0",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-flash": "1.4.3",
    "ember-cli-htmlbars": "^1.0.10",
    "ember-cli-htmlbars-inline-precompile": "^0.3.3",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-jshint": "^2.0.1",
    "ember-cli-qunit": "^3.0.1",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "^6.2.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-composable-helpers": "2.0.3",
    "ember-concurrency": "0.8.7",
    "ember-data": "^2.12",
    "ember-date-fns": "0.3.0",
    "ember-export-application-global": "^1.0.5",
    "ember-font-awesome": "3.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-models-table": "1.12.0",
    "ember-power-select": "1.8.5",
    "ember-power-select-blockless": "0.3.1",
    "ember-resolver": "^2.0.3",
    "ember-screen": "0.2.0",
    "ember-toggle": "4.0.2",
    "ember-truth-helpers": "1.3.0",
    "emberfire": "2.0.7",
    "liquid-fire": "0.27.3",
    "loader.js": "^4.0.10",
    "torii": "0.9.5"
  },
  "engines": {
    "node": ">= 0.12.0"
  },
  "private": true,
  "dependencies": {}
}

**Comment by dirkdirk** [comment]
Tested on a fresh ember app with:
```
  "devDependencies": {
    "bootstrap": "3.3.7",
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^2.4.1",
    "ember-bootstrap": "1.0.0-rc.1",
    "ember-bootstrap-power-select": "1.0.0-alpha.1",
    "ember-cli": "2.10.0",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-htmlbars": "^1.0.10",
    "ember-cli-htmlbars-inline-precompile": "^0.3.3",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-jshint": "^2.0.1",
    "ember-cli-qunit": "^3.0.1",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.10.0",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-power-select": "1.9.4",
    "ember-power-select-blockless": "0.3.1",
    "ember-resolver": "^2.0.3",
    "ember-welcome-page": "^1.0.3",
    "loader.js": "^4.0.10"
  },
```

Ran ember server and got:
```
The Broccoli Plugin: [BroccoliMergeTrees: Addon#compileAddon(ember-basic-dropdown) ] failed with:
TypeError: The plugin [null,{"envFlags":{"source":"@glimmer/env","flags":{"DEBUG":true,"CI":false}},"externalizeHelpers":{"global":"Ember"},"debugTools":{"source":"@ember/debug","assertPredicateIndex":1}}] didn't export a Plugin instance
    at PluginManager.validate (/Users/Dirk/www/test-ember/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/Dirk/www/test-ember/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/Dirk/www/test-ember/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/Dirk/www/test-ember/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/Dirk/www/test-ember/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at /Users/Dirk/www/test-ember/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:102:26
    at initializePromise (/Users/Dirk/www/test-ember/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/Users/Dirk/www/test-ember/node_modules/rsvp/dist/rsvp.js:1039:33)
    at Object.transformString (/Users/Dirk/www/test-ember/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:101:12)
    at Babel.transform (/Users/Dirk/www/test-ember/node_modules/broccoli-babel-transpiler/index.js:110:22)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/Dirk/www/test-ember/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/Dirk/www/test-ember/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/Users/Dirk/www/test-ember/node_modules/broccoli-merge-trees/index.js:36:53)
    at mergeTrees (/Users/Dirk/www/test-ember/node_modules/ember-cli/lib/models/addon.js:32:14)
    at Class.compileAddon (/Users/Dirk/www/test-ember/node_modules/ember-cli/lib/models/addon.js:747:12)
    at Class.treeForAddon (/Users/Dirk/www/test-ember/node_modules/ember-cli/lib/models/addon.js:514:26)
    at Class._treeFor (/Users/Dirk/www/test-ember/node_modules/ember-cli/lib/models/addon.js:371:33)
    at Class.treeFor (/Users/Dirk/www/test-ember/node_modules/ember-cli/lib/models/addon.js:339:21)
    at /Users/Dirk/www/test-ember/node_modules/ember-cli/lib/models/addon.js:254:34
    at Array.map (native)
```

Downgraded to ember-power-select 1.8.5 and all's well.

**Comment by dirkdirk** [comment]
I'm having issues installing other addons also.  It must have something to do with my setup.

Closing this issue for now.  I'll report back once I'm 100% sure it's not my system and the problem persists.
